services:
  - type: web
    name: gate-entry
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m

