apiVersion: v1
kind: Service
metadata:
  name: gate-entry-service
  labels:
    app: gate-entry
spec:
  type: NodePort
  selector:
    app: gate-entry
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080


